version: '3.6'

services: 
    db-dbi:
        image: mysql
        restart: unless-stopped
        environment: 
            MYSQL_ROOT_PASSWORD: passme
            MYSQL_DATABASE: dbi
        ports:
          - 3308:3308
        volumes:
            - './drive:/var/opt/dbi'